# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('meow_volume', models.PositiveSmallIntegerField(default=2)),
                ('breed', models.CharField(max_length=15)),
                ('coat_type', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('bark_volume', models.PositiveSmallIntegerField(default=6)),
                ('breed', models.CharField(max_length=15)),
                ('coat_description', models.CharField(max_length=45)),
                ('wags_per_second', models.FloatField(default=3.0)),
            ],
        ),
    ]
