# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('volume', models.PositiveSmallIntegerField()),
                ('breed', models.CharField(max_length=15)),
                ('coat', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'example_models_pets',
                'managed': False,
            },
        ),
    ]
